// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVZSgMGwNM9E4C6OoKNtP2O-ynZB5o8E',
    appId: '1:108877943104:web:58e1dff1913f5886ee6aa5',
    messagingSenderId: '108877943104',
    projectId: 'vsl-final',
    authDomain: 'vsl-final.firebaseapp.com',
    storageBucket: 'vsl-final.appspot.com',
    measurementId: 'G-WTG9FZ2GWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwCcu4KtXcADI4V8UnNxd1YjU6JDDa3Q',
    appId: '1:108877943104:android:8d1ace213b26abfdee6aa5',
    messagingSenderId: '108877943104',
    projectId: 'vsl-final',
    storageBucket: 'vsl-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIduHvk026JsOt0RGxZyA8X_1azqrB-IU',
    appId: '1:108877943104:ios:8566ac0d7a6f569bee6aa5',
    messagingSenderId: '108877943104',
    projectId: 'vsl-final',
    storageBucket: 'vsl-final.appspot.com',
    iosBundleId: 'com.example.smarthomeFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIduHvk026JsOt0RGxZyA8X_1azqrB-IU',
    appId: '1:108877943104:ios:8566ac0d7a6f569bee6aa5',
    messagingSenderId: '108877943104',
    projectId: 'vsl-final',
    storageBucket: 'vsl-final.appspot.com',
    iosBundleId: 'com.example.smarthomeFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVZSgMGwNM9E4C6OoKNtP2O-ynZB5o8E',
    appId: '1:108877943104:web:e19669d28800464fee6aa5',
    messagingSenderId: '108877943104',
    projectId: 'vsl-final',
    authDomain: 'vsl-final.firebaseapp.com',
    storageBucket: 'vsl-final.appspot.com',
    measurementId: 'G-XMGJ20NFNW',
  );
}
